// Mocks generated by Mockito 5.4.4 from annotations
// in libarary_gen/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/material.dart' as _i6;
import 'package:libarary_gen/models/book.dart' as _i4;
import 'package:libarary_gen/services/book_service.dart' as _i2;
import 'package:libarary_gen/services/settings_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BookService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookService extends _i1.Mock implements _i2.BookService {
  MockBookService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Book>> getAllBooks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);

  @override
  _i3.Future<_i4.Book?> getBookById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i3.Future<_i4.Book?>.value(),
      ) as _i3.Future<_i4.Book?>);

  @override
  _i3.Future<void> addBook(_i4.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #addBook,
          [book],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateBook(_i4.Book? book) => (super.noSuchMethod(
        Invocation.method(
          #updateBook,
          [book],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBook(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Book>> searchBooks(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [query],
        ),
        returnValue: _i3.Future<List<_i4.Book>>.value(<_i4.Book>[]),
      ) as _i3.Future<List<_i4.Book>>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i5.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i6.ThemeMode> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i3.Future<_i6.ThemeMode>.value(_i6.ThemeMode.system),
      ) as _i3.Future<_i6.ThemeMode>);

  @override
  _i3.Future<void> setThemeMode(_i6.ThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
